name: Build release artifact

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose --release
      
    - name: Archive release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-markdown
        path: |
          target/release/permsearch
